In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

# County FIPS data aquired from 
https://www.census.gov/geographies/reference-files/2017/demo/popest/2017-fips.html

In [2]:
file="MNcounty-geocodes-v2017.csv"
fips_df=pd.read_csv(file)
fips_df.head()

,Summary Level,State Code (FIPS),County Code (FIPS),County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description)
0,10,0,0,0,0,0,United States
1,40,1,0,0,0,0,Alabama
2,50,1,1,0,0,0,Autauga County
3,50,1,3,0,0,0,Baldwin County
4,50,1,5,0,0,0,Barbour County

# Select out Minnesota counties only

In [3]:
mn_fips=fips_df[fips_df['State Code (FIPS)'] == 27]
mn_fips=mn_fips[mn_fips['County Subdivision Code (FIPS)'] == 0]
mn_fips=mn_fips[mn_fips['Place Code (FIPS)'] == 0]
mn_fips=mn_fips[mn_fips['County Code (FIPS)'] != 0]
mn_fips= mn_fips[["State Code (FIPS)","County Code (FIPS)","Area Name (including legal/statistical area description)"]]
mn_fips.head()

,State Code (FIPS),County Code (FIPS),Area Name (including legal/statistical area description)
15969,27,1,Aitkin County
15970,27,3,Anoka County
15971,27,5,Becker County
15972,27,7,Beltrami County
15973,27,9,Benton County

In [4]:
mn_fips=mn_fips.rename(columns={"State Code (FIPS)":"statefips","County Code (FIPS)":"countyfips","Area Name (including legal/statistical area description)":"county"})
mn_fips.head()

       statefips  countyfips           county
15969         27           1    Aitkin County
15970         27           3     Anoka County
15971         27           5    Becker County
15972         27           7  Beltrami County
15973         27           9    Benton County

# remove 'County' from name and make lower case

In [5]:
new_county=[]
for row in mn_fips['county']:
    if row[0] != 'C':
        cnty=row.split('C')[0].lower() 
    elif row == 'Crow Wing County':
        cnty = 'crow wing'
    else:
        cnty=row.split(' ')[0].lower()
    print(cnty)
    new_county.append(cnty)
mn_fips['county']=new_county
mn_fips.head()

aitkin
anoka
becker
beltrami
benton
big stone
blue earth
brown
carlton
carver
cass
chippewa
chisago
clay
clearwater
cook
cottonwood
crow wing
dakota
dodge
douglas
faribault
fillmore
freeborn
goodhue
grant
hennepin
houston
hubbard
isanti
itasca
jackson
kanabec
kandiyohi
kittson
koochiching
lac qui parle
lake
lake of the woods
le sueur
lincoln
lyon
mcleod
mahnomen
marshall
martin
meeker
mille lacs
morrison
mower
murray
nicollet
nobles
norman
olmsted
otter tail
pennington
pine
pipestone
polk
pope
ramsey
red lake
redwood
renville
rice
rock
roseau
st. louis
scott
sherburne
sibley
stearns
steele
stevens
swift
todd
traverse
wabasha
wadena
waseca
washington
watonwan
wilkin
winona
wright
yellow medicine

       statefips  countyfips     county
15969         27           1    aitkin
15970         27           3     anoka
15971         27           5    becker
15972         27           7  beltrami
15973         27           9    benton

# Tableau requires state and country also

In [6]:
mn_fips["state"]= 'minnesota'
mn_fips["country"] = 'united states'
mn_fips.head()

       statefips  countyfips     county      state        country
15969         27           1    aitkin   minnesota  united states
15970         27           3     anoka   minnesota  united states
15971         27           5    becker   minnesota  united states
15972         27           7  beltrami   minnesota  united states
15973         27           9    benton   minnesota  united states

In [7]:
mn_fips.to_csv('mnCountyFIPS.csv', index=False,header=True,encoding='utf-8')